### ISSUE TITLE
Geometry issue with selection tool

### ISSUE THREAD

**Issue by rouelibre1** [a-b-street/ltn#57] opened 2024-05-22 09:20 UTC
Hi, as described here https://github.com/a-b-street/ltn/issues/56#issuecomment-2124236997 I've faced some weird geometry/result with the selection tool on my favourite neighborhood:

![332730214-87070c7f-8df1-45d3-ac9d-169876d549ae](https://github.com/a-b-street/ltn/assets/73238613/d850766c-3c02-46fe-a592-cd3982fbb848)

[ltn_Test.zip](https://github.com/a-b-street/ltn/files/15401004/ltn_Test.zip)

Here's a link to a video screencapture of what happens : https://transfert.free.fr/9Qnjbvm (valid for 30 days)

**Comment by dabreegster** [comment] 2024-05-31 16:48
The problem is that there aren't any roads towards the west to capture the area you're selecting. Here's the "debug route snapper" results:
![image](https://github.com/a-b-street/ltn/assets/1664407/9aab152b-52a6-4f0c-a905-130155421af5)

You could try importing a larger area and stretching more west. In trying to do this myself, I hit a few more problems, so starting a list:

- [ ] The route snapper state is not getting cleared out in every case. Edit existing neighbourhood, import a new area, saw some bugs with old state
- [ ] Try displaying the snappable nodes and edges (also desired for https://github.com/acteng/atip/issues/504)
- [ ] The station here is causing some extra strangeness from the lack of any roads, so being able to mix in some freehand points could be helpful

**Comment by dabreegster** [comment] 2024-06-27 14:54
Sorry for the long wait! If you try again, there's a new option to show all snappable points. Here's the problem more clearly visible:
![image](https://github.com/a-b-street/ltn/assets/1664407/55ce2f06-f2d1-4683-9405-3e07242eed1a)
... though I'm still finding some funny bugs when re-importing larger areas, will work on those

**Comment by dabreegster** [comment] 2024-11-26 19:22
I've made a new version of the tool for drawing areas; try it at https://acteng.github.io/atip/files.html?authority=TA_South%20Yorkshire%20Combined%20Authority&schema=v2. You can mix snapped and freehand waypoints by clicking to toggle. I'll try and bring it over to this project soon, which will be one way to manually override when some of the snapping goes wrong.

**Comment by dabreegster** [comment] 2024-12-13 16:15
Please give this a try again! I started with the file you sent:
![image](https://github.com/user-attachments/assets/3d3c0b10-6f98-43b2-9785-cf24ef28763a)
There were some overlapping and out-of-order waypoints (now obvious with the numbering). I'm not sure what boundary you were going for originally, but by clicking red waypoints to make them freehand I could stretch over the station:
![image](https://github.com/user-attachments/assets/10736376-b584-49fa-bf8a-3d2214e64205)
Winding up with:
![image](https://github.com/user-attachments/assets/2a0aebd4-f965-4bc3-b176-b29c95a43f76)

Let me know if you're able to create the boundary you wanted with this update (and maybe with importing a larger study area to begin with)

**Comment by TFCx** [comment] 2024-12-13 23:32
Seeing you're looking for feedback: the new algorithm is way more intuitive. It's really convenient when a railroad / river (somekind of not-road line) is delimiting a district.

The only bug I may have spotted (it might no be a bug) is when clicking on a grey dot between 2 red/snapped waypoints: it doesn't insert a new red/snapped waypoint. To do so, I need to drag the point from and back to its original location.

**Comment by dabreegster** [comment] 2024-12-14 15:13
Good point, it does feel intuitive to just click a grey dot to immediately make it a waypoint. Now you can click it or do the same dragging.

I'll close this issue out, but please file another / reopen if you have more issues. Thanks!

**Closed by dabreegster** 2024-12-14 15:13 UTC
